config/routes.rb
TestChat::Application.routes.draw do

  get "logout" => "sessions#destroy"
  get "login" => "sessions#new"
  get "signup" => "users#new"
  
  resources :password_resets
  resources :users
  resources :sessions
  resources :companies
  resources :channels

  root :to => 'main#index'
  match '/ch/:chat_id' => "channels#show"
  match '/register' => "companies#new"
  

end

app/models/channel.rb
class Channel < ActiveRecord::Base
  attr_accessible :uuid, :name
  
  validates_presence_of :uuid, :name
  validates_uniqueness_of :uuid
  
  belongs_to :company
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :name, :email, :logo, :description
  
  validates_presence_of :name, :email
  
  has_many :channels
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery! do |config|
    config.reset_password_mailer = UserMailer
  end

  attr_accessible :email, :password, :password_confirmation, :companyId

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :loginRedirect, :except => [:new, :create, :destroy]

  def loginRedirect
    # Secondary filter that I couldn't put into the before_filter clause
    unless request.fullpath == '/'
      if not current_user
        redirect_to '/login'
      end
    end
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  def new
  end

  def index
  end

  def create
  end
  
  def show
  end

  def destroy
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def new
    @company = Company.new
    @user = User.new
  end

  def index
    # admin feature for listing all companies that are registered
    @allCompanies = Company.all
  end

  def create
    # Can't simply create the two models in one step as the company is optional
    # and so not all users will have a company associated with them
    @company = Company.new(params[:company])
    if @company.save
      @user = User.new(params[:user])
      # Manually associate the optional company
      @user.companyId = @company.id
      if @user.save
        # ZZZ this should redirect to the company admin dashboard
        redirect_to root_url, :notice => "Signed up!"
      else
        redirect_to new_company_url, :notice => "Invalid user details"
      end
    else
      redirect_to new_company_url, :notice => "Invalid company details"
    end
  end

  def destroy
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def show

  end

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    skip_before_filter :require_login
  
    # request password reset.
    # you get here when the user entered his email in the reset password form and submitted it.
    def create 
      @user = User.find_by_email(params[:email])
      
      # This line sends an email to the user with instructions on how to reset their password (a url with a random token)
      @user.deliver_reset_password_instructions! if @user
      
      # Tell the user instructions have been sent whether or not email was found.
      # This is to not leak information to attackers about which emails exist in the system.
      redirect_to(root_path, :notice => 'Instructions have been sent to your email.')
    end
  
    # This is the reset password form.
    def edit
      @user = User.load_from_reset_password_token(params[:id])
      @token = params[:id]
      not_authenticated if !@user
    end
    
    # This action fires when the user has sent the reset password form.
    def update
      @user = User.load_from_reset_password_token(params[:token])
      not_authenticated if !@user
      # the next line clears the temporary token and updates the password
      if @user.reset_password!(params[:user])
        redirect_to(root_path, :notice => 'Password was successfully updated.')
      else
        render :action => "edit"
      end
    end
end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
  def index
    # Setup data required for registering a new client
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
      
  end
  
  def create
    user = login(params[:email], params[:password], params[:remember_me])
    if user
      # ZZZ needs to redirect to either the dashboard OR the chat page
      redirect_back_or_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Email or password was invalid"
      render :new
    end
  end
  
  def destroy
    logout
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/channels/create.html.erb
<h1>Channels#create</h1>
<p>Find me in app/views/channels/create.html.erb</p>

app/views/channels/index.html.erb
<h1>Channels#index</h1>
<p>Find me in app/views/channels/index.html.erb</p>

app/views/channels/new.html.erb
<h1>Channels#new</h1>
<p>Find me in app/views/channels/new.html.erb</p>

app/views/channels/show.html.erb
<div class="legendText">Welcome <%= current_user.email %></div>
<div id="postsarea">
  <ul id='chats'>
    <li class='template'><div class='chat round'><div class='item_img'>default image</div><div class='item_msg'>default message</div></div></li>
  </ul>
</div>
<div class="post_input"><textarea cols="50" rows="4" ></textarea></div>
<input type='button' id='addChat' value='Send' />

app/views/companies/create.html.erb
<h1>Companies#create</h1>
<p>Find me in app/views/companies/create.html.erb</p>

app/views/companies/index.html.erb
<div class="textTitle">Company list</div>
<div class="blindlink"><%= link_to "Add company", new_company_path %></div>
<%
for company in @allCompanies do
%>
  <div class="blindlink"><%= link_to company.name, company %></div>
<%
end
%>

app/views/companies/new.html.erb
<div class="displayText">Registration</div>
<%= form_tag(companies_path, :method=>'post') do %>
<div>
  <fieldset>
    <legend><span class="legendText">Company</span></legend>
    <div class="field">
      <%= label :company, :name %>
      <%= text_field :company, :name %>
    </div>
    <div class="field">
      <%= label :company, :email %>
      <%= text_field :company, :email %>
    </div>
    <div class="field">
      <%= label :company, :logo %>
      <%= text_field :company, :logo %>
    </div>
    <div class="field">
      <%= label :company, :description %>
      <%= text_area :company, :description %>
    </div>
  </fieldset>
  <fieldset>
    <legend><span class="legendText">Default user</span></legend>
    <div class="field">
      <%= label :user, :email %>
      <%= text_field :user, :email %>
    </div>
    <div class="field">
      <%= label :user, :password %>
      <%= text_field :user, :password %>
    </div>
    <div class="field">
      <%= label :user, :password_confirmation %>
      <%= text_field :user, :password_confirmation %>
    </div>
  </fieldset>
  <div><%= submit_tag "Save" %></div>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <span class="copytext">Copyright &copy; 2011 Stanzr</span>
</div>

app/views/layouts/_header.html.erb
<div id="header">
  <div id="headLogo"><a href="http://blog.stanzr.com/" class="blindlink"><em>powered by</em> Stanzr</a></div>
<%
  # Don't show our general login links on the landing page
  unless (request.fullpath == '/' or request.fullpath == '/login')
%>
  <ul id="topnav">
    <li class="navgroup-left">
      <a id="head_linkedin" class="first sprite-linkedin16" href="/api/user/oauth/linkedin/login/aoschadlin"></a>
    </li>
    <li class="navgroup-left">
      <a id="head_twitter" class="sprite-twitter16" href="/api/user/oauth/twitter/login/aoschadlin"></a>
    </li>
    <li class="navgroup-left">
      <a id="head_facebook" class="sprite-facebook16" href="/api/user/oauth/facebook/login/aoschadlin"></a>
    </li>
    <li class="navgroup-left"><%= link_to "Sign in", login_path %></li>
  </ul>
<%
  end
%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestChat</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div id="container">
      <%= render 'layouts/header'%>
      <div class="content round">
        <% flash.each do |key, value| %>
          <div class="mandatory <%= key %> "><%= value %></div>
        <% end %>
        <%= yield %>
      </div>
      <%= render 'layouts/footer'%>
      <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>

app/views/main/index.html.erb
<div>
  <div class="displayTextTitle"><em>Stanzr</em><div>
  <div class="displayText">Real-Time Social Media Group</div>
  <div class="displayText">Chats for B2B Marketing</div>
</div>
<div class="userChoice">
  <div>
    <a href="/register" class="pretty_button_lge">Start a conversation!</a>
  </div>
</div>

app/views/main/show.html.erb
<h2>Welcome <%= session[:username] %></h2>
<div id="postsarea">
  <ul id='chats'>
    <li class='template'><div class='chat round'><div class='item_img'>default image</div><div class='item_msg'>default message</div></div></li>
  </ul>
</div>
<div class="post_input"><textarea cols="50" rows="4" ></textarea></div>
<input type='button' id='addChat' value='Send' />

app/views/password_resets/_form.html.erb
 <%= form_for @user, :url => password_reset_path(@user), :html => {:method => :put} do |f| %>
    <div class="field">
    	<%= f.label :email %><br />
      <%= @user.email %>
    </div>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
  	<%= hidden_field_tag :token, @token %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/register/index.html.erb
<h1>Ask user for information about their company</h1>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>